### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zhangsj** [jhao104/django-blog#5]
python manage.py makemigrations blog
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
  File "/root/blog/lib/python2.6/site-packages/django/__init__.py", line 3, in <module>
    from django.utils.version import get_version
  File "/root/blog/lib/python2.6/site-packages/django/utils/version.py", line 7, in <module>
    from django.utils.lru_cache import lru_cache
  File "/root/blog/lib/python2.6/site-packages/django/utils/lru_cache.py", line 28
    fasttypes = {int, str, frozenset, type(None)},

**Comment by jhao104** [comment]
@zhangsj  你的Python版本不对，你是用的CentOS上默认的2.6吧？

**Comment by zhangsj** [comment]
是的，谢谢了

**Comment by jhao104** [comment]
@zhangsj 不客气
